import type {
  AdminStat,
  Announcement,
  Banner,
  Course,
  CreditWallet,
  Deal,
  EmailCampaign,
  FaqItem,
  MemberProfile,
  MembershipPlan,
  Reservation,
  ReservableOffering,
  SegmentTag,
  ThemeSettings,
  ToolItem,
  WaitlistEntry,
} from "@/lib/types";

export const sampleThemeSettings: ThemeSettings = {
  brandName: "DDS Members",
  heroHeadline: "学びと実践を一つの体験にまとめる会員サイト",
  primaryColor: "#1238c6",
  accentColor: "#f6c453",
  surfaceColor: "#f5f1e8",
  logoWordmark: "DDS",
  supportEmail: "support@dds.example",
  termsNotice: "クレジットの他者付与・譲渡はできません。",
};

export const sampleMembershipPlans: MembershipPlan[] = [
  {
    code: "HOBBY",
    name: "DDS Hobby",
    monthlyCreditGrant: 4,
    rolloverCap: 10,
    unlimitedCredits: false,
    cycleBasis: "calendar_month",
    heroLabel: "まずは習慣化から",
    description: "毎月4回の予約と、Hobby公開の教材・イベントに参加可能。",
  },
  {
    code: "BIZ",
    name: "DDS Biz",
    monthlyCreditGrant: 4,
    rolloverCap: 10,
    unlimitedCredits: false,
    cycleBasis: "contract_date",
    heroLabel: "実務で使う前提の強化プラン",
    description: "毎月4回の予約と、Bizまでの限定教材・イベントに参加可能。",
  },
  {
    code: "PRO",
    name: "DDS Pro",
    monthlyCreditGrant: 0,
    rolloverCap: 999,
    unlimitedCredits: true,
    cycleBasis: "contract_date",
    heroLabel: "全解放・無制限",
    description: "全講義視聴、全講義予約参加、クレジット無限。",
  },
];

export const sampleSegments: SegmentTag[] = [
  { id: "seg-plan-hobby", slug: "plan:hobby", label: "DDS Hobby", isSystem: true },
  { id: "seg-plan-biz", slug: "plan:biz", label: "DDS Biz", isSystem: true },
  { id: "seg-plan-pro", slug: "plan:pro", label: "DDS Pro", isSystem: true },
  { id: "seg-ai-foundation", slug: "ai-foundation", label: "AI基礎" },
  { id: "seg-sales-lab", slug: "sales-lab", label: "営業実践ラボ" },
  { id: "seg-mentor", slug: "mentor-access", label: "個別メンター" },
];

export const sampleUsers: MemberProfile[] = [
  {
    id: "user-admin",
    name: "DDS 管理者",
    email: "admin@dds.example",
    role: "super_admin",
    status: "active",
    planCode: "PRO",
    segmentSlugs: ["plan:pro", "mentor-access"],
    joinedAt: "2026-01-02T09:00:00+09:00",
    contractStartAt: "2026-01-02T09:00:00+09:00",
    title: "プロダクトオーナー",
    avatarLabel: "AD",
    demoPassword: "admin-demo",
  },
  {
    id: "user-staff",
    name: "DDS スタッフ",
    email: "staff@dds.example",
    role: "staff",
    status: "active",
    planCode: "BIZ",
    segmentSlugs: ["plan:biz", "sales-lab"],
    joinedAt: "2026-01-10T09:00:00+09:00",
    contractStartAt: "2026-01-10T09:00:00+09:00",
    title: "サポート責任者",
    avatarLabel: "ST",
    demoPassword: "staff-demo",
  },
  {
    id: "user-hobby",
    name: "佐藤 里奈",
    email: "hobby@dds.example",
    role: "student",
    status: "active",
    planCode: "HOBBY",
    segmentSlugs: ["plan:hobby", "ai-foundation"],
    joinedAt: "2026-02-01T09:00:00+09:00",
    contractStartAt: "2026-02-01T09:00:00+09:00",
    title: "副業スタート期",
    avatarLabel: "SR",
    demoPassword: "student-demo",
  },
  {
    id: "user-biz",
    name: "山田 大輔",
    email: "biz@dds.example",
    role: "student",
    status: "active",
    planCode: "BIZ",
    segmentSlugs: ["plan:biz", "ai-foundation", "sales-lab"],
    joinedAt: "2026-01-20T09:00:00+09:00",
    contractStartAt: "2026-01-20T09:00:00+09:00",
    title: "営業自動化に注力",
    avatarLabel: "YD",
    demoPassword: "student-demo",
  },
  {
    id: "user-pro",
    name: "高橋 未来",
    email: "pro@dds.example",
    role: "student",
    status: "active",
    planCode: "PRO",
    segmentSlugs: ["plan:pro", "mentor-access", "sales-lab"],
    joinedAt: "2026-01-05T09:00:00+09:00",
    contractStartAt: "2026-01-05T09:00:00+09:00",
    title: "事業拡大フェーズ",
    avatarLabel: "TM",
    demoPassword: "student-demo",
  },
];

export const sampleBanners: Banner[] = [
  {
    id: "ban-01",
    eyebrow: "今週の実践導線",
    title: "毎日の作業会で学びを前に進める",
    subtitle: "Zoomリンクと課題提出フォームを1画面に集約しました。",
    ctaLabel: "作業会を見る",
    ctaHref: "/app/bookings",
    accent: "from-sky-200 via-blue-100 to-indigo-200",
  },
  {
    id: "ban-02",
    eyebrow: "受講生限定",
    title: "厳選AIツールの法人割引を公開中",
    subtitle: "お得情報から比較表と特典コードを確認できます。",
    ctaLabel: "お得情報へ",
    ctaHref: "/app/deals",
    accent: "from-amber-100 via-yellow-100 to-orange-200",
    audience: { planCodes: ["BIZ", "PRO"] },
  },
  {
    id: "ban-03",
    eyebrow: "Pro Priority",
    title: "個別メンタリング優先予約を開始",
    subtitle: "Pro会員は通常枠より48時間早く先行予約できます。",
    ctaLabel: "優先枠を見る",
    ctaHref: "/app/bookings",
    accent: "from-violet-200 via-fuchsia-100 to-rose-200",
    audience: { planCodes: ["PRO"] },
  },
];

export const sampleAnnouncements: Announcement[] = [
  {
    id: "ann-01",
    title: "3月の教材アップデート",
    summary: "AI営業台本、プロンプト設計、案件獲得テンプレートを追加しました。",
    body: "オンライン教材タブから最新コースを確認できます。Biz以上には営業テンプレートの追加章も公開済みです。",
    publishedAt: "2026-03-04T12:00:00+09:00",
  },
  {
    id: "ann-02",
    title: "イベント申込後の参加リンク表示を改善",
    summary: "申込確定後にマイページの予約履歴から参加URLへ直接アクセスできます。",
    body: "待機から繰り上げになった場合も、メールと会員サイト内で案内されます。",
    publishedAt: "2026-03-02T10:00:00+09:00",
  },
  {
    id: "ann-03",
    title: "Pro限定オフィスアワーを毎週木曜に実施",
    summary: "講師への壁打ち、案件相談、進捗確認をまとめて対応します。",
    body: "Pro会員はクレジット無制限で参加できます。",
    publishedAt: "2026-02-27T09:30:00+09:00",
    audience: { planCodes: ["PRO"] },
  },
];

export const sampleDeals: Deal[] = [
  {
    id: "deal-01",
    title: "Bunny Stream 55%OFF 紹介枠",
    summary: "会員向けの動画配信基盤優待。教材を安全に配信したい人向け。",
    badge: "会員限定",
    offer: "月額55%OFF",
    ctaLabel: "特典を確認",
    ctaHref: "#",
    audience: { planCodes: ["BIZ", "PRO"] },
  },
  {
    id: "deal-02",
    title: "音声教材収録セット割",
    summary: "ポッドキャスト教材の制作向けに、収録マイクと編集テンプレートをセット化。",
    badge: "人気",
    offer: "初回3万円OFF",
    ctaLabel: "詳細を見る",
    ctaHref: "#",
  },
  {
    id: "deal-03",
    title: "Pro限定 1on1壁打ち延長枠",
    summary: "通常60分のメンタリングを90分に延長できる特別オファー。",
    badge: "Pro",
    offer: "延長無料",
    ctaLabel: "申請する",
    ctaHref: "#",
    audience: { planCodes: ["PRO"] },
  },
];

export const sampleTools: ToolItem[] = [
  {
    id: "tool-01",
    title: "案件ヒアリングシート",
    summary: "初回商談で要件を漏らさず整理するための質問テンプレート。",
    body: "Google Docs で複製してすぐに使える形式です。",
    href: "#",
  },
  {
    id: "tool-02",
    title: "プロンプト検証シート",
    summary: "検証条件、改善履歴、出力比較を一元管理できます。",
    body: "AI基礎から提案営業まで幅広く対応。",
    href: "#",
  },
  {
    id: "tool-03",
    title: "営業スクリプトセット",
    summary: "Biz以上向けの電話・DM・Zoom 商談台本をまとめました。",
    body: "成果が出たフレーズだけを抽出した最新版です。",
    href: "#",
    audience: { planCodes: ["BIZ", "PRO"] },
  },
];

export const sampleFaqs: FaqItem[] = [
  {
    id: "faq-01",
    category: "予約",
    question: "使わなかったクレジットはどうなりますか？",
    answer:
      "Hobby/Biz は毎月4回付与され、未使用分は総保有上限まで繰り越されます。初期設定は上限10回です。",
  },
  {
    id: "faq-02",
    category: "予約",
    question: "クレジットを他の会員へ渡せますか？",
    answer:
      "できません。クレジットの他者付与・譲渡は不可です。管理画面からの手動付与は運営側のみ可能です。",
  },
  {
    id: "faq-03",
    category: "教材",
    question: "動画教材はどこで視聴できますか？",
    answer:
      "オンライン教材タブからコースを開き、レッスン単位で動画・記事・ポッドキャストを視聴できます。",
  },
  {
    id: "faq-04",
    category: "プラン",
    question: "Pro だと何が違いますか？",
    answer:
      "全講義視聴、全講義予約参加、Pro専用イベント参加、クレジット無制限が利用できます。",
  },
];

export const sampleCourses: Course[] = [
  {
    id: "course-01",
    slug: "start-dash",
    title: "0. DDSスタートダッシュ",
    summary: "最初の7日で環境構築と学習導線を整える導入コース。",
    heroNote: "まずは最短で学びを回し始める",
    estimatedHours: "3.5h",
    modules: [
      {
        id: "mod-01",
        title: "第1章: ビジネス環境の設計",
        lessons: [
          {
            id: "les-01",
            slug: "choose-your-stack",
            title: "講義1: 学習と仕事を両立する作業環境",
            summary: "集中が切れにくいツール構成と初期設定を整えます。",
            type: "video",
            duration: "12m",
            blocks: [
              {
                id: "blk-hero-01",
                type: "hero",
                eyebrow: "Lesson 01",
                title: "作業環境を先に整える",
                body: "学習の継続率は最初のセットアップで決まります。PC・カレンダー・メモ・収録環境を一気に整えます。",
              },
              {
                id: "blk-video-01",
                type: "embed_video",
                title: "環境構築ガイド",
                url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
                duration: "12:14",
              },
              {
                id: "blk-check-01",
                type: "checklist",
                title: "この講義で終えること",
                items: [
                  "カレンダーに学習時間を固定する",
                  "教材視聴用のブックマークを整理する",
                  "録音・録画環境を確認する",
                ],
              },
            ],
          },
          {
            id: "les-02",
            slug: "prompt-basics",
            title: "講義2: プロンプト設計の基本",
            summary: "AIに渡す前提条件の整理方法を学びます。",
            type: "article",
            duration: "8m",
            blocks: [
              {
                id: "blk-rich-01",
                type: "rich_text",
                title: "プロンプトの型",
                body:
                  "前提条件・目的・出力形式・禁止事項の4つを固定すると、品質のブレが減ります。毎回ゼロから書かず、テンプレート化してください。",
              },
              {
                id: "blk-accordion-01",
                type: "accordion",
                title: "よくある詰まりどころ",
                items: [
                  {
                    title: "指示が曖昧",
                    body: "対象読者、出力フォーマット、長さを明示します。",
                  },
                  {
                    title: "検証条件がない",
                    body: "成功/失敗の判定軸を最初に置きます。",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "mod-02",
        title: "第2章: 学習サイクルの定着",
        lessons: [
          {
            id: "les-03",
            slug: "weekly-review",
            title: "講義3: 週次レビューの回し方",
            summary: "行動量と成果を1枚で振り返るレビュー方法。",
            type: "podcast",
            duration: "18m",
            blocks: [
              {
                id: "blk-audio-01",
                type: "embed_audio",
                title: "音声レビューガイド",
                url: "https://open.spotify.com/embed/episode/7makk4oTQel546B0PZlDM5",
                duration: "18:03",
              },
              {
                id: "blk-cta-01",
                type: "cta",
                title: "週次レビューシートを使う",
                body: "毎週1回、予約参加の前にこのシートを更新してください。",
                label: "シートを開く",
                href: "#",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "course-02",
    slug: "sales-automation-lab",
    title: "営業自動化ラボ",
    summary: "提案設計から商談後フォローまでをAIで省力化する実践コース。",
    heroNote: "Biz以上で公開",
    estimatedHours: "5.2h",
    audience: { planCodes: ["BIZ", "PRO"] },
    modules: [
      {
        id: "mod-03",
        title: "第1章: 商談準備",
        lessons: [
          {
            id: "les-04",
            slug: "proposal-blueprint",
            title: "講義1: 提案書の骨子を作る",
            summary: "案件情報から提案の叩き台を生成するフロー。",
            type: "video",
            duration: "16m",
            blocks: [
              {
                id: "blk-video-02",
                type: "embed_video",
                title: "提案書作成フロー",
                url: "https://www.youtube.com/embed/oHg5SJYRHA0",
                duration: "16:08",
              },
              {
                id: "blk-download-01",
                type: "download",
                title: "提案書テンプレート",
                description: "営業自動化ラボで使う提案シートです。",
                href: "#",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "course-03",
    slug: "pro-strategy-room",
    title: "Pro戦略会議アーカイブ",
    summary: "上位会員向けの戦略壁打ち、案件レビュー、チーム設計のアーカイブ。",
    heroNote: "Pro限定",
    estimatedHours: "7.4h",
    audience: { planCodes: ["PRO"] },
    modules: [
      {
        id: "mod-04",
        title: "第1章: 収益設計",
        lessons: [
          {
            id: "les-05",
            slug: "premium-offer-design",
            title: "講義1: 高単価オファーの設計",
            summary: "単価を上げるときに外してはいけない前提を整理します。",
            type: "article",
            duration: "11m",
            blocks: [
              {
                id: "blk-rich-02",
                type: "rich_text",
                title: "高単価化の基本",
                body:
                  "価格ではなく成果責任の範囲を再設計します。約束する成果、必要工数、再現性の順に整理してください。",
              },
            ],
          },
        ],
      },
    ],
  },
];

export const sampleOfferings: ReservableOffering[] = [
  {
    id: "off-01",
    slug: "daily-coworking-march-10",
    title: "毎日作業会",
    summary: "進捗共有と短時間の質問対応を組み合わせた定例枠。",
    description: "毎朝30分で今日やることを宣言し、終わりに成果を報告する会です。",
    offeringType: "booking",
    startsAt: "2026-03-10T09:00:00+09:00",
    endsAt: "2026-03-10T09:30:00+09:00",
    locationLabel: "Zoom",
    capacity: 30,
    waitlistEnabled: false,
    creditRequired: 1,
    consumptionMode: "on_confirm",
    refundDeadline: "2026-03-10T08:30:00+09:00",
    externalJoinUrl: "#",
    priceLabel: "クレジット 1",
    host: "DDSサポート",
    featured: true,
  },
  {
    id: "off-02",
    slug: "mindset-seminar-march-11",
    title: "マインドセットセミナー",
    summary: "副業・事業フェーズの切り替えに必要な思考整理。",
    description: "現状分析、理想状態、次の30日でやるべき行動を明確にします。",
    offeringType: "event",
    startsAt: "2026-03-11T20:00:00+09:00",
    endsAt: "2026-03-11T21:00:00+09:00",
    locationLabel: "Zoom",
    capacity: 40,
    waitlistEnabled: true,
    creditRequired: 1,
    consumptionMode: "on_attend",
    refundDeadline: "2026-03-11T18:00:00+09:00",
    externalJoinUrl: "#",
    priceLabel: "限定イベント",
    host: "みかみ講師",
    featured: true,
  },
  {
    id: "off-03",
    slug: "biz-proposal-lab-march-14",
    title: "提案書ラボ",
    summary: "営業資料をその場で添削する少人数セッション。",
    description: "Biz以上対象。各自の提案書を画面共有し、改善点をリアルタイムで整理します。",
    offeringType: "booking",
    startsAt: "2026-03-14T19:00:00+09:00",
    endsAt: "2026-03-14T20:30:00+09:00",
    locationLabel: "Zoom",
    capacity: 8,
    waitlistEnabled: true,
    creditRequired: 1,
    consumptionMode: "on_confirm",
    refundDeadline: "2026-03-13T19:00:00+09:00",
    externalJoinUrl: "#",
    priceLabel: "Biz以上",
    host: "営業責任者",
    featured: false,
    audience: { planCodes: ["BIZ", "PRO"] },
  },
  {
    id: "off-04",
    slug: "pro-office-hours-march-17",
    title: "Proオフィスアワー",
    summary: "講師と個別に近い距離で壁打ちする優先枠。",
    description: "Pro限定。案件相談、提案レビュー、採用設計など何でも扱います。",
    offeringType: "event",
    startsAt: "2026-03-17T18:00:00+09:00",
    endsAt: "2026-03-17T19:00:00+09:00",
    locationLabel: "Zoom",
    capacity: 12,
    waitlistEnabled: true,
    creditRequired: 1,
    consumptionMode: "on_confirm",
    refundDeadline: "2026-03-16T18:00:00+09:00",
    externalJoinUrl: "#",
    priceLabel: "Pro限定",
    host: "DDS代表",
    featured: true,
    audience: { planCodes: ["PRO"] },
  },
];

export const sampleReservations: Reservation[] = [
  {
    id: "res-01",
    offeringId: "off-01",
    userId: "user-hobby",
    status: "confirmed",
    createdAt: "2026-03-05T09:00:00+09:00",
  },
  {
    id: "res-02",
    offeringId: "off-03",
    userId: "user-biz",
    status: "confirmed",
    createdAt: "2026-03-04T16:00:00+09:00",
  },
  {
    id: "res-03",
    offeringId: "off-04",
    userId: "user-pro",
    status: "confirmed",
    createdAt: "2026-03-06T11:00:00+09:00",
  },
];

export const sampleWaitlistEntries: WaitlistEntry[] = [
  {
    id: "wait-01",
    offeringId: "off-03",
    userId: "user-hobby",
    createdAt: "2026-03-06T18:20:00+09:00",
  },
];

export const sampleWallets: CreditWallet[] = [
  {
    userId: "user-hobby",
    currentBalance: 3,
    thisCycleGranted: 4,
    thisCycleConsumed: 1,
    carriedOver: 0,
    nextGrantAt: "2026-04-01T00:00:00+09:00",
    ledger: [
      {
        id: "led-01",
        userId: "user-hobby",
        type: "monthly_grant",
        amount: 4,
        createdAt: "2026-03-01T00:00:00+09:00",
        note: "3月分の基本付与",
      },
      {
        id: "led-02",
        userId: "user-hobby",
        type: "consumed",
        amount: -1,
        createdAt: "2026-03-05T09:00:00+09:00",
        note: "毎日作業会を予約",
        offeringId: "off-01",
      },
    ],
  },
  {
    userId: "user-biz",
    currentBalance: 8,
    thisCycleGranted: 4,
    thisCycleConsumed: 0,
    carriedOver: 4,
    nextGrantAt: "2026-03-20T00:00:00+09:00",
    ledger: [
      {
        id: "led-03",
        userId: "user-biz",
        type: "monthly_grant",
        amount: 4,
        createdAt: "2026-02-20T00:00:00+09:00",
        note: "2月分の基本付与",
      },
      {
        id: "led-04",
        userId: "user-biz",
        type: "bonus_grant",
        amount: 4,
        createdAt: "2026-03-01T00:00:00+09:00",
        note: "営業ラボ実践ボーナス",
      },
    ],
  },
  {
    userId: "user-pro",
    currentBalance: 999,
    thisCycleGranted: 0,
    thisCycleConsumed: 0,
    carriedOver: 0,
    nextGrantAt: "常時",
    ledger: [],
  },
  {
    userId: "user-admin",
    currentBalance: 999,
    thisCycleGranted: 0,
    thisCycleConsumed: 0,
    carriedOver: 0,
    nextGrantAt: "常時",
    ledger: [],
  },
  {
    userId: "user-staff",
    currentBalance: 4,
    thisCycleGranted: 4,
    thisCycleConsumed: 0,
    carriedOver: 0,
    nextGrantAt: "2026-03-10T00:00:00+09:00",
    ledger: [
      {
        id: "led-05",
        userId: "user-staff",
        type: "monthly_grant",
        amount: 4,
        createdAt: "2026-03-10T00:00:00+09:00",
        note: "3月分の基本付与",
      },
    ],
  },
];

export const sampleCampaigns: EmailCampaign[] = [
  {
    id: "camp-01",
    title: "3月イベント告知",
    subject: "今週の講義予約と限定イベントのお知らせ",
    status: "scheduled",
    scheduledAt: "2026-03-08T08:00:00+09:00",
    audience: { planCodes: ["HOBBY", "BIZ", "PRO"] },
  },
  {
    id: "camp-02",
    title: "Proオフィスアワー告知",
    subject: "Pro限定のオフィスアワー枠を公開しました",
    status: "draft",
    audience: { planCodes: ["PRO"] },
  },
];

export const sampleAdminStats: AdminStat[] = [
  { label: "有効会員", value: "184", note: "前月比 +14" },
  { label: "今週の予約数", value: "62", note: "待機 7件" },
  { label: "公開教材", value: "48", note: "下書き 12本" },
  { label: "配信予定メール", value: "3", note: "本日 08:00 配信あり" },
];
